# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: 	macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        repository: uglide/RedisDesktopManager
        path: rdm
        submodules: true
        ref: 2020
    # install python3  
    - name: install Python3
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    # pip install 
    - name: pip install
      uses: BSFishy/pip-action@v1
      with:
        requirements: rdm/src/py/requirements.txt
        upgrade: true
    # install xcode
    - name: install xcode
      uses: sinoru/actions-setup-xcode@v1.1
      with:
        xcode-version: '10.0'    
    # install QT   
    - name: install QT
      uses: jurplel/install-qt-action@v2
      with: 
        modules: 'qtcharts'
    # Runs a single command using the runners shell
    - name: build
      run: |
        cd rdm/src/resources/
        cp Info.plist.sample Info.plist
        sed -i '.back' 's/0.0.0/2020.0/g' Info.plist
        cd $GITHUB_WORKSPACE/rdm/src
        sed -i '.back' 's/^\(\s*\)VERSION=.*/\1VERSION=2020.0/g' rdm.pro
        mkdir -p $GITHUB_WORKSPACE/rdm/bin/osx/release
        touch $GITHUB_WORKSPACE/rdm/bin/osx/release/setup.cfg
        cd $GITHUB_WORKSPACE/rdm/bin/osx/release/
        echo '[install]\nprefix=' > setup.cfg
        cd $GITHUB_WORKSPACE/rdm/src
        qmake CONFIG-=debug CONFIG+=sdk_no_version_check
        make -s -j 8
        cd $GITHUB_WORKSPACE/rdm/bin/osx/release
        macdeployqt Redis\ Desktop\ Manager.app -qmldir=../../../src/qml
        
      
